### ISSUE TITLE
Error on ubuntu 15.10

### ISSUE THREAD

**Issue by bet0x** [jniltinho/smb4manager#9]
Error on ubuntu 15.10
`
alberto@storage:~/smb4manager$ ./create_env.sh
Running virtualenv with interpreter /usr/bin/python2
New python executable in flask/bin/python2
Not overwriting existing python script flask/bin/python (you must use flask/bin/python2)
Installing setuptools, pip...done.
Requirement already satisfied (use --upgrade to upgrade): Flask==0.10.1 in ./flask/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): Flask-Admin==1.0.6 in ./flask/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): Flask-Cache==0.12 in ./flask/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): Flask-Login==0.1.3 in ./flask/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): Flask-Themes==0.1.3 in ./flask/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): Flask-Uploads==0.1.3 in ./flask/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): Flask-WTF==0.8.3 in ./flask/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): Jinja2==2.7 in ./flask/lib/python2.7/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe==0.18 in ./flask/lib/python2.7/site-packages (from -r requirements.txt (line 9))
Requirement already satisfied (use --upgrade to upgrade): Rocket==1.2.4 in ./flask/lib/python2.7/site-packages (from -r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): WTForms==1.0.4 in ./flask/lib/python2.7/site-packages (from -r requirements.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): Werkzeug==0.9.1 in ./flask/lib/python2.7/site-packages (from -r requirements.txt (line 12))
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in ./flask/lib/python2.7/site-packages (from Flask==0.10.1->-r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): distribute in ./flask/lib/python2.7/site-packages (from Rocket==1.2.4->-r requirements.txt (line 10))
Requirement already satisfied (use --upgrade to upgrade): setuptools>=0.7 in ./flask/lib/python2.7/site-packages (from distribute->Rocket==1.2.4->-r requirements.txt (line 10))
Cleaning up...
Production ...
./runserver.py
Production and Debug ...
./runserver.py --debug
alberto@storage:~/smb4manager$ find . -type f -iname *.pyc -exec rm  -f {} \;
alberto@storage:~/smb4manager$ ./runserver.py --debug
Traceback (most recent call last):
  File "./runserver.py", line 17, in <module>
    from app import app
  File "/home/alberto/smb4manager/app/__init__.py", line 12, in <module>
    app.config.from_object('app.configuration')
  File "/home/alberto/smb4manager/flask/local/lib/python2.7/site-packages/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/home/alberto/smb4manager/flask/local/lib/python2.7/site-packages/werkzeug/utils.py", line 424, in import_string
    sys.exc_info()[2])
  File "/home/alberto/smb4manager/flask/local/lib/python2.7/site-packages/werkzeug/utils.py", line 417, in import_string
    __import__(modname)
  File "/home/alberto/smb4manager/app/configuration.py", line 14, in <module>
    import os, sys, samba
werkzeug.utils.ImportStringError: import_string() failed for 'app.configuration'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'app' found in '/home/alberto/smb4manager/app/__init__.py'.
- 'app.configuration' not found.

Original exception:

ImportError: No module named samba
alberto@storage:~/smb4manager$
`

**Comment by jniltinho** [comment]
Hi @bet0x  smb4manager not run Ubuntu 15*, Sorry! :-(
rewrite smb4manager for Golang, coming soon
New SMB4Manager full (Ubuntu, CentOS, OpenSUSE)

TODO: first alpha release (2016 November)
New SMB4Manager
Lang: Golang
Framework: Beego
Support: All Linux Distro
Frontend: Boostrap + Jquery
Motivation: Final Paper (TCC)

**Comment by bet0x** [comment]
Why Golang, is a mess and python is better!
